### ISSUE TITLE
npm run build-minified error

### ISSUE THREAD

**Issue by SevenBlocks** [sqren/fb-sleep-stats#1]
"npm run build-minified" gives the error:

ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (.../fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (.../fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (.../fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (.../fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127

**Comment by whizzzkid** [comment]
Got the same

**Comment by whizzzkid** [comment]
The issue is with the node version. Requires version 4

https://github.com/webpack/css-loader/issues/145

**Comment by SevenBlocks** [comment]
Good catch. Upgrading to version 4 worked for me.

**Comment by sorenlouv** [comment]
Yes, Node 4 is required. Glad you got it fixed. Will update the readme to point this out.
