### ISSUE TITLE
Cant get it to work on Raspberry Pi 2

### ISSUE THREAD

**Issue by Horkyze** [sqren/fb-sleep-stats#81]
I installed npm without problem. 

After running `npm install` and `npm run webpack` I get the following error:
The `node_modules` dir was empty.

`ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/pi/Apps/fb-sleep-stats/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/pi/Apps/fb-sleep-stats/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/pi/Apps/fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/pi/Apps/fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127`

Here is the full console log:
http://pastebin.com/raw/pSFg4fMv

I decided to ignore the error and run scrape anyway, but all I got was:
`Polling every 600 seconds
Tue Mar 15 2016 00:08:06 GMT+0100 (CET)  - Active users:  63 / 258
Tue Mar 15 2016 00:08:06 GMT+0100 (CET) An error occured while scraping. Please check to make sure your development.json config is correct [ReferenceError: Promise is not defined]`

This is my development.json (not real values ofc..)
`{
    "fbCookie": {
        "c_user": "2431254960",
        "xs": "539%3A2b6ALG3g4H1nWQ%3A2%3A1657993299%3A1012"
    },
    "pollingInterval": 600,
    "appId": 534315541561821,
    "server": {
        "port": 3000
    }
}`

BTW I am running pi-hole to block ads, hope that wont be an issue.

**Comment by sorenlouv** [comment]
This seems to be a duplicate of https://github.com/sqren/fb-sleep-stats/issues/75. Updating Node to the latest version should fix it.

**Comment by aleknak** [comment]
take a look at [#98](https://github.com/sqren/fb-sleep-stats/issues/98)
