### ISSUE TITLE
[Error: Could not retrieve Facebook users] - Problem with two factor authentication enabled accounts?

### ISSUE THREAD

**Issue by BinaryAlps** [sqren/fb-sleep-stats#83]
When I run `npm run scrape` I get this error: 

> [Error: Could not retrieve Facebook users] 

Is there a possible problem with Facebook accounts that have two factor authentication enabled? 

With `npm start` I can accede the page on the localhost but it shows me the log in button. After clicking it and giving the app the needed permission the list is still empty.

**Comment by BinaryAlps** [comment]
Complete error message:
`Error getting buddyList. Will fallback to other means of retrieving friends [TypeError: Cannot read property '0' of undefined]
TypeError: Cannot read property '1' of null
    at /Users/username/Downloads/fb-sleep-stats-master/node_modules/fb-sleep/index.js:39:81
    at tryCatcher (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/username/Downloads/fb-sleep-stats-master/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-03-16 21:56:30 An error occured while scraping. Please check to make sure your development.json config is correct [Error: Could not retrieve Facebook users]
`

**Comment by irfanshaik11** [comment]
did you do
 npm run webpack
 after you updated the development.json file?

the development.json file edits aren't considered unless you run that

**Comment by BinaryAlps** [comment]
Yes. 
I updated the _development.json_, run _npm run scrape_, then run _npm start_. 
The _npm run scrape_ commend throws the exception. _npm start_ works fine.

**Comment by erny83** [comment]
I've the same problem "Error getting buddyList. Will fallback to other means of retrieving friends [Error: No users found]"

**Comment by wanfry** [comment]
I had the same issue. The problem was in the xs code. Verify xs and c_user values.

**Comment by sorenlouv** [comment]
Make sure you don't copy the quotes (`"`), don't have any trailing whitespace, and that you copy the _entire_ xs code.

**Comment by marianstiehler** [comment]
I seem to have the same issue.

> Error getting buddyList. Will fallback to other means of retrieving friends [Error: No users found]
> 2016-04-03 22:24:02  - Active users:  2 / 76

Should be much more active users.

This is my development.json config; for privacy and security reasons I have shaken up the values a bit (c_user, xs, appId are not real!). 

Do I have to omit a " or something?

```
  "fbCookie": {
        "c_user": "111111111",
        "xs": "13A3AzBnYNA14597135321L56Jvn56%%wg2%3%3A16141"
    },
    "pollingInterval": 600,
    "appId": 477104363548681,
    "server": {
        "port": 3000
    }
}
```

**Comment by excodex** [comment]
Same error occurred here.

> Error getting buddyList. Will fallback to other means of retrieving friends [TypeError: Cannot read property '0' of undefined]
> 6/26/2016, 7:31:19 AM  - Active users:  37 / 98

I have 234 friends on Facebook.

**Comment by trych** [comment]
I have the same issue. Is it correct that the xs value can contain the % symbol?

**Comment by destedge** [comment]
Same here.  I have more than 250

```
Error getting buddyList. Will fallback to other means of retrieving friends [TypeError: Cannot read property '0' of undefined]
2016-08-19 17:38:15 - Active users: 17 / 76
```

**Comment by ruggertech** [comment]
same here.
The problem is with the underlying library fb-sleep.
It fails during the function getUsers

To work around this error temporarily 
1. go into node_modules -> fb_sleep -> index.js
2. change the function get users by adding remarks (or just copy paste the below)

Taking a look at the file index.js of the library fb-sleep, you'd see that even though you receive a failing message, the function falls back to a different way of retrieving the users and succeeds. 

```


fbSleep.getUsers = function(config) {
    validateConfig(config);

            var activeUsersRequest = fbSleep.fetchActiveUsers(config);
            var lastActiveTimesRequest = fbSleep.getLastActiveTimes(config);

            return Bluebird.all([activeUsersRequest, lastActiveTimesRequest])
               .spread(function(activeUsers, lastActiveTimes) {
                   return _.merge(activeUsers, lastActiveTimes);
               });

};

```
