### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by niyazialpay** [sqren/fb-sleep-stats#98]
When I enter the command line "npm run webpack" I give an error

> fb-sleep-stats@0.9.0 webpack /root/fb-sleep-stats
> webpack --progress

Hash: 4a711a63075eff90b928  
Version: webpack 1.13.1
Time: 23234ms
    Asset    Size  Chunks             Chunk Names
bundle.js  2.3 MB       0  [emitted]  main
    + 353 hidden modules

ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/root/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/root/fb-sleep-stats/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/root/fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/root/fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127

**Comment by aleknak** [comment]
1. `rm -rf node_modules/`
2. set css-loader version to "^0.18.0" in package.json
3. `npm install`
4. `npm run webpack`

worked for me...
